// Generated by SolidPython 0.4.7 on 2020-04-13 18:19:41


cylinder($fn = 50, h = 10, r = 5);
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from solid import *
from solid.utils import *
d = cylinder(r=5,h=10)
d.add_param('$fn',50)

scad_render_to_file(d,"tube.scad")
 
 
************************************************/
